import os

#OUTBREAK_START = "Wayne"
OUTBREAK_START = "Pennsylvania"

INITIAL_ESCAPE_CHANCE_H = 0.25
FINAL_ESCAPE_CHANCE_H = 0.99
ESCAPE_LEARNING_RATE_H = 1
ESCAPE_LEARNING_THRESHOLD_H = 1
COMBAT_LEARNING_RATE_H = .1
COMBAT_LEARNING_THRESHOLD_H = 2
INITIAL_ESCAPE_CHANCE_Z = 0.99
FINAL_ESCAPE_CHANCE_Z = 0.01
ZED_SPEED = 1 #mph
ENCOUNTER_DISTANCE = 30 #ft
DAYS_TO_SIMULATE = 2000
VIDEO_FILENAME = "Zombie Apocalypse Simulation.gif"
PLOT_TITLE = "Zombie Apocalypse Simulator"
FPS = 4
ANIMATION_DURATION = 30
TIME_PROGRESSION = "log" #Must be "lin" or "log"
COLOR_SLICES = 64
ALPHA_SLICES = 32

DATA_DIRECTORY = "./data"
SHAPE_DIRECTORY = os.path.join(DATA_DIRECTORY,"shapefiles")
NEIGHBOR_DIRECTORY = os.path.join(DATA_DIRECTORY,"neighbors")
POPULATION_DIRECTORY = os.path.join(DATA_DIRECTORY,"populations")

SHAPEFILE_FILENAME_SUFFIX = "_shapefile.shp"
NEIGHBORS_FILENAME_SUFFIX = "_neighbors.json"
STATE_POPULATIONS_FILENAME = os.path.join(POPULATION_DIRECTORY,"state_populations.csv")
COUNTY_POPULATIONS_FILENAME = os.path.join(POPULATION_DIRECTORY,"county_populations.csv")

LAST_SIMULATION_FILENAME = "last_simulation.sim"