import os

DEFAULT_REGION = "US"
OUTBREAK_START = "Wayne"

INITIAL_ESCAPE_CHANCE_H = 0.5
FINAL_ESCAPE_CHANCE_H = 0.99
INITIAL_ESCAPE_CHANCE_Z = 0.99
FINAL_ESCAPE_CHANCE_Z = 0.1
BORDER_POROSITY = 0.1
ZED_SPEED = 1 #mph
ENCOUNTER_DISTANCE = 30 #ft
DAYS_TO_SIMULATE = 150
VIDEO_FILENAME = "Zombie Apocalypse Simulation.gif"
PLOT_TITLE = "Zombie Apocalypse Simulator"
FPS = 10
ANIMATION_DURATION = 10
TIME_PROGRESSION = "lin" #Must be "lin" or "log"
COLORMAP = "RdYlGn"
VMIN = 0
VMAX = 1

DATA_DIRECTORY = "./data"
SHAPE_DIRECTORY = os.path.join(DATA_DIRECTORY,"shapefiles")
NEIGHBOR_DIRECTORY = os.path.join(DATA_DIRECTORY,"neighbors")
POPULATION_DIRECTORY = os.path.join(DATA_DIRECTORY,"populations")

SHAPEFILE_FILENAME_SUFFIX = "_shapefile.shp"
NEIGHBORS_FILENAME_SUFFIX = "_neighbors.json"
STATE_POPULATIONS_FILENAME = os.path.join(POPULATION_DIRECTORY,"state_populations.csv")
COUNTY_POPULATIONS_FILENAME = os.path.join(POPULATION_DIRECTORY,"county_populations.csv")

LAST_SIMULATION_FILENAME = "last_simulation.sim"